# Generated by Django 5.2 on 2025-05-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
